package com.odanylchuk.cosmocatsmarketplace.exception;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.*;

/**
 * RFC 9457 compliant Problem Details for HTTP APIs.
 * See: <a href="https://www.rfc-editor.org/rfc/rfc9457.html">...</a>
 */
@Value
@Builder(toBuilder = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ErrorResponse {

    /**
     * A URI reference that identifies the problem type.
     * Defaults to "about:blank" when not present.
     */
    @Builder.Default
    String type = "about:blank";

    /**
     * A short, human-readable summary of the problem type.
     */
    String title;

    /**
     * The HTTP status code generated by the origin server.
     */
    Integer status;

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    String detail;

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    String instance;
}
