package com.odanylchuk.cosmocatsmarketplace.exception;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.*;

import java.util.List;

/**
 * RFC 9457 compliant Problem Details for HTTP APIs with validation extensions.
 * See: https://www.rfc-editor.org/rfc/rfc9457.html
 *
 * Extends the standard problem details with an "errors" field for validation failures.
 */
@Value
@Builder(toBuilder = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ValidationError {

    /**
     * A URI reference that identifies the problem type.
     */
    @Builder.Default
    String type = "about:blank";

    /**
     * A short, human-readable summary of the problem type.
     */
    String title;

    /**
     * The HTTP status code generated by the origin server.
     */
    Integer status;

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    String detail;

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    String instance;

    /**
     * Extension field: List of validation errors.
     * This is a problem-specific extension as allowed by RFC 9457.
     */
    List<ParamsViolationDetails> errors;
}
